In [4]:
import numpy as np

In [6]:
# Create a NumPy array containing 10, 20, 30, 40, 50
arr1 = np.array([i*10 for i in range(1,6)])
print(arr1)

[10 20 30 40 50]


In [13]:
#Exercise 2: Check Array Properties
arr = np.array([[1, 2, 3],[4, 5, 6]])
#Print Shape
print("Shape: ", arr.shape)
#Print Dimensions
print("Dimension: ", arr.ndim)
# Print data type
print("Data Type:", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Data Type: int64


int

In [17]:
#Exercise 3: Generate Zeros Array
# Create a 3x4 array filled with zeros
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
# Create an array containing even numbers from 2 to 20
arr = np.array([i for i in range(2,21,2)])
print(arr)
#or
arr = np.array([i for i in range(2,21) if not i%2]) # or if i%2 == 0
print(arr)

#or 
arr = np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]


In [30]:
# Exercise 5: Reshape an Array
# Convert the array into 3 rows and 4 columns
arr = np.arange(1, 13)
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
#Exercise 6: Find Maximum and Minimum
import numpy as np
arr = np.array([25, 40, 10, 90, 65])
# Print maximum value
print("Max =", arr.max())
# Print minimum value
print("Min =", arr.min())

Max = 90
Min = 10


In [34]:
#Exercise 7: Array Arithmetic
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])
# Add both arrays
result = arr1 + arr2
print(result)

[11 22 33 44]


In [35]:
#Exercise 8: Filter Elements
import numpy as np
arr = np.array([5, 12, 18, 7, 25, 30])
# Select elements greater than 15
result = arr[arr > 15]
print(result)

[18 25 30]


In [37]:
#Exercise 9: Calculate Mean
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
# Calculate average value
avg = arr.mean()
print(avg)


30.0


In [42]:
# Exercise 10: Matrix Multiplication
import numpy as np
A = np.array([[1, 2],
 [3, 4]])
B = np.array([[5, 6],
 [7, 8]])
# Perform matrix multiplication
C = A @ B 
print(C)
#orrr
C = A.dot(B)
print(C)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [47]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
# Replace all values greater than 15 with 100
arr[arr>15] = 100
print(arr)


[  5  10  15 100 100]
